import { Navbar } from "@/component/Navbar";
import { Footer } from "@/component/Footer";
import { FrederickatheGreat } from "../../utils/fonts";
import { scriptImports } from "../../utils/ScriptImports";
import "../../utils/styleLinks.css";
import Head from "next/head";
import Script from "next/script";

export const metadata = {
  title: "BigT | Infotech Solution",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
        <script
          src="https://maps.googleapis.com/maps/api/js?key=YOUR_API_KEY&callback=init"
          async
          defer
        ></script>
      </Head>
      <div className={FrederickatheGreat.className}>
        <Navbar />
        {children}
        <Footer />
        {scriptImports.map((src, index) => (
          <Script key={index} src={src} strategy="beforeInteractive" />
        ))}
      </div>
    </html>
  );
}
